loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('categoria/', include('categoria.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name="criar"),
    path('atualizar/', views.Atualizar.as_view(), name="atualizar"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),

]

perfil/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ValidationError
import re
from utils.validacpf import valida_cpf


class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    idade = models.PositiveIntegerField()
    data_nascimento = models.DateField()
    cpf = models.CharField(max_length=11)
    cep = models.CharField(max_length=8)
    endereco = models.CharField(max_length=50)
    numero = models.CharField(max_length=5)
    bairro = models.CharField(max_length=30)
    complemento = models.CharField(max_length=30, blank=True, null=True)
    cidade = models.CharField(max_length=30)
    estado = models.CharField(max_length=2)
        # default='SP',
        # choices=(

        #     ('AC', 'Acre'),
        #     ('AL', 'Alagoas'),
        #     ('AP', 'Amapá'),
        #     ('AM', 'Amazonas'),
        #     ('BA', 'Bahia'),
        #     ('CE', 'Ceará'),
        #     ('DF', 'Distrito Federal'),
        #     ('ES', 'Espírito Santo'),
        #     ('GO', 'Goiás'),
        #     ('MA', 'Maranhão'),
        #     ('MT', 'Mato Grosso'),
        #     ('MS', 'Mato Grosso do Sul'),
        #     ('MG', 'Minas Gerais'),
        #     ('PA', 'Pará'),
        #     ('PB', 'Paraíba'),
        #     ('PR', 'Paraná'),
        #     ('PE', 'Pernambuco'),
        #     ('PI', 'Piauí'),
        #     ('RJ', 'Rio de Janeiro'),
        #     ('RN', 'Rio Grande do Norte'),
        #     ('RS', 'Rio Grande do Sul'),
        #     ('RO', 'Rondônia'),
        #     ('RR', 'Roraima'),
        #     ('SC', 'Santa Catarina'),
        #     ('SP', 'São Paulo'),
        #     ('SE', 'Sergipe'),
        #     ('TO', 'Tocantins'),
        # )
    
    def __str__(self):
        return f'{self.usuario}'

    def clean(self):
        error_messages = {}

        cpf_enviado = self.cpf or None
        cpf_salvo = None
        perfil = Perfil.objects.filter(cpf=cpf_enviado).first()

        if perfil:
            cpf_salvo = perfil.cpf

            if cpf_salvo is not None and self.pk != perfil.pk:
                error_messages['cpf'] = 'CPF já existe.'

        if not valida_cpf(self.cpf):
            error_messages['cpf'] = 'Digite um cpf válido'

        if re.search(r'[^0-9]', self.cep) or len(self.cep) < 8:
            error_messages['cep'] = 'CEP inválido, digite os 8 digitos do cep.'

        if error_messages:
            raise ValidationError(error_messages)

    class meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfis'

perfil/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class PerfilForm(forms.ModelForm):
    class Meta:
        model = models.Perfil
        fields = '__all__'
        exclude = ('usuario',)

class UserForm(forms.ModelForm):
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Senha',
        help_text='Se você já estiver logado, pode deixar os campos de senha em branco'
    )

    password2 = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Confirmação senha',
    )

    def __init__(self, usuario=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.usuario = usuario

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password', 'password2', 'email')

    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data
        validation_error_msgs = {}

        usuario_data = cleaned.get('username')
        email_data = cleaned.get('email')
        password_data = cleaned.get('password')
        password2_data = cleaned.get('password2')        

        usuario_db = User.objects.filter(username=usuario_data).first()
        email_db = User.objects.filter(email=email_data).first()
         
        error_msg_user_exists = 'Usuário já existe'
        error_msg_email_exists = 'Email já existe'
        error_msg_password_match = 'As duas senhas não conferem'
        error_msg_password_short = 'A sua senha precisa ter pelo menos 6 caracteres'
        error_msg_required_field = 'Este campo é obrigatório'


        # usuários logados
        if self.usuario:
            if usuario_data != usuario_db.username:
                if usuario_db:
                    validation_error_msgs['username'] = error_msg_user_exists
        
            if email_data != email_db.email:
                validation_error_msgs['email'] = error_msg_email_exists
        
            if password_data:
                if password_data != password2_data:
                    validation_error_msgs['password'] = error_msg_password_match
                    validation_error_msgs['password2'] = error_msg_password_match

            if len(password_data) < 6:
                validation_error_msgs['password'] = error_msg_password_short

                        
        # usuários não logados
        else:
            if usuario_db:
                validation_error_msgs['username'] = error_msg_user_exists
            
            if email_db:
                validation_error_msgs['email'] = error_msg_email_exists
            
            if not password_data:
                validation_error_msgs['password'] = error_msg_required_field

            if not password2_data:
                validation_error_msgs['password2'] = error_msg_required_field

            if password_data != password2_data:
                validation_error_msgs['password'] = error_msg_password_match
                validation_error_msgs['password2'] = error_msg_password_match
            
            if len(password_data) < 6:
                validation_error_msgs['password'] = error_msg_password_short
            
        if validation_error_msgs:
            raise(forms.ValidationError(validation_error_msgs))

perfil/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views import View
from django.http import HttpResponse
from .models import Perfil
from . import forms
import copy
from django.contrib import messages
# from django.contrib.admin.views.decorators import staff_member_required
# from django.utils.decorators import method_decorator


# @method_decorator(staff_member_required, name='dispatch')
class BasePerfil(View):
    template_name = 'perfil/criar.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.carrinho = copy.deepcopy(self.request.session.get('carrinho', {}))

        self.perfil = None

        if self.request.user.is_authenticated:
            self.perfil = Perfil.objects.filter(usuario=self.request.user).first()

            self.contexto = {
                'userform': forms.UserForm(
                    data=self.request.POST or None,
                    usuario=self.request.user,
                    instance=self.request.user,
                ),
                'perfilform': forms.PerfilForm(
                    data=self.request.POST or None,
                    instance=self.perfil
                )
            }
        else:
            self.contexto = {
                'userform': forms.UserForm(data=self.request.POST or None),
                'perfilform': forms.PerfilForm(data=self.request.POST or None)
            }

        self.userform = self.contexto['userform']
        self.perfilform = self.contexto['perfilform']

        if self.request.user.is_authenticated:
            self.template_name = 'perfil/atualizar.html'

        self.renderizar = render(
            self.request, self.template_name, self.contexto)

    def get(self, *args, **kwargs):
        return self.renderizar


class Criar(BasePerfil):
    def post(self, *args, **kwargs):
        if not self.userform.is_valid() or not self.perfilform.is_valid():

            messages.error(self.request,
            "Existem erros no formulário de cadastro. Verifique"
            " se todos os campos foram preenchidos corretamente.")

            return self.renderizar

        username = self.userform.cleaned_data.get('username') 
        password = self.userform.cleaned_data.get('password') 
        email = self.userform.cleaned_data.get('email') 
        first_name = self.userform.cleaned_data.get('first_name') 
        last_name = self.userform.cleaned_data.get('last_name') 

        # usuario logado
        if self.request.user.is_authenticated:
            usuario = get_object_or_404(User, username=self.request.user.username)
            usuario.username = username

            if password:
                usuario.set_password(password)
            
            usuario.email = email
            usuario.first_name = first_name
            usuario.last_name = last_name
            usuario.save()

            if not self.perfil:
                self.perfilform.cleaned_data['usuario'] = usuario
                perfil = Perfil(**self.perfilform.cleaned_data)
                perfil.save()
            else:
                perfil = self.perfilform.save(commit=False)
                perfil.usuario = usuario
                perfil.save()

        # usuario nao logado(novo)
        else:
            pass
            usuario = self.userform.save(commit=False)
            usuario.set_password(password)
            usuario.save()

            perfil = self.perfilform.save(commit=False)
            perfil.usuario = usuario
            perfil.save()

        if password:
            autentica = authenticate(
                self.request,
                username=usuario,
                password=password
            )

        if autentica:
            login(self.request, user=usuario)

        self.request.session['carrinho'] = self.carrinho
        self.request.session.save()

        messages.success(self.request,
        'Seu cadastro foi criado ou atualizado com sucesso.')


        messages.success(self.request,
        'Você fez login e pode concluir sua compra.')

        return redirect('produto:carrinho')

        return self.renderizar



class Atualizar(View):
    def get(self, *args, **kwargs):
        return HttpResponse('Atualizar')


class Login(View):
    def post(self, *args, **kwargs):
        username = self.request.POST.get('username')
        password = self.request.POST.get('password')

        if not username or not password:
            messages.error(self.request,
            'Usuário ou senha inválidos.'
        )
            return redirect('perfil:criar')

        usuario = authenticate(self.request, username=username, password=password)

        if not usuario:
            messages.error(self.request,
            'Usuário ou senha inválidos.'
        )
            return redirect('perfil:criar')
            
        login(self.request, user=usuario)

        messages.success(self.request,
            'Login realizado com sucesso.'
        )

        return redirect('produto:carrinho')


class Logout(View):
    def get(self, *args, **kwargs):
        carrinho = copy.deepcopy(self.request.session.get('carrinho'))
        logout(self.request)

        self.request.session['carrinho'] = carrinho
        self.request.session.save()

        return redirect('produto:lista')

perfil/templates/perfil/atualizar.html
{% extends 'perfil/criar.html' %}

{% block titulo %}Atualizar perfil de {{ user }} | {% endblock %}

{% block titulocadastro %}
<h4>Atualizar Cadastro</h4>
<p>
    Utilize o formulário abaixo para atualizar seus dados.
</p>
{% endblock %}

perfil/templates/perfil/criar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Criar perfil | {% endblock %}

{% load crispy_forms_tags %}



{% block conteudo %}

<div class="row">

    {% if not request.user.is_authenticated %}
    <div class="col-lg mt-3">
        <h4>Login</h4>
        <p>Se você já fez cadastro, basta entrar com seu usuário e senha abaixo:</p>

        <form method="POST" action="{% url 'perfil:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="InputUsuario1">Usuário</label>
                <input type="text" name="username" class="form-control" id="InputUsuario1"
                    aria-describedby="usuarioHelp" placeholder="Digite seu usuário">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Senha:</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1"
                    placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary btn-block btn-lg">Entrar</button>
        </form>

    </div>
    {% endif %}

    <div class="col-lg mt-3">

        {% block titulocadastro %}
        <h4>Cadastro</h4>
        <p>Caso ainda não tenha cadastro, utilize o formulário abaixo a seguir para se cadastrar</p>
        {% endblock %}

        <form method="POST" action="">
            {% csrf_token %}
            {{ userform|crispy }}
            {{ perfilform|crispy }}

            <div class="row">
                <div class="col">
                    <button type='submit' class='btn btn-primary btn-block btn-lg'>
                        Enviar
                    </button>
                </div>
            </div>
        </form>

    </div>
</div>
{% endblock %}
{% block js %}

    
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
crossorigin="anonymous"></script>

<script>
    $(document).ready(function() {

        function limpa_formulário_cep() {
            // Limpa valores do formulário de cep.
            $("#id_endereco").val("");
            $("#id_bairro").val("");
            $("#id_cidade").val("");
            $("id_estado").val("");
        }
        
        //Quando o campo cep perde o foco.
        $("#id_cep").blur(function() {
            //Nova variável "cep" somente com dígitos.
            var cep = $(this).val().replace(/\D/g, '');

            //Verifica se campo cep possui valor informado.
            if (cep != "") {

                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;

                //Valida o formato do CEP.
                if(validacep.test(cep)) {

                    //Preenche os campos com "..." enquanto consulta webservice.
                    $("#id_endereco").val("...");
                    $("#id_bairro").val("...");
                    $("#id_cidade").val("...");
                    $("#id_estado").val("...");

                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                        if (!("erro" in dados)) {
                        
                            //Atualiza os campos com os valores da consulta.
                            $("#id_endereco").val(dados.logradouro);
                            $("#id_bairro").val(dados.bairro);
                            $("#id_cidade").val(dados.localidade);
                            $("#id_estado").val(dados.uf);
                        } //end if.
                        else {
                            //CEP pesquisado não foi encontrado.
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                } //end if.
                else {
                    //cep é inválido.
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                }
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpa_formulário_cep();
            }
        });
    });



</script>
{% endblock js %}